services:
  - type: web
    name: ml-studio-api
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: UPLOAD_DIR
        value: ./uploads
      - key: CORS_ORIGINS
        value: https://ml-studio-zeta.vercel.app,http://localhost:3000
      - key: FRONTEND_URL
        value: https://ml-studio-zeta.vercel.app
      - key: PORT
        value: "10000"
